service: ecommerce-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${opt:stage, "dev"}
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    RAZORPAY_KEY_ID: ${env:RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${env:RAZORPAY_KEY_SECRET}
    RAZORPAY_WEBHOOK_SECRET: ${env:RAZORPAY_WEBHOOK_SECRET}
    HOST_URL: ${env:HOST_URL}
    PORT: ${env:PORT}

package:
  individually: true
  patterns:
    - dist/**
    - node_modules/**
    - package.json

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: "*"
